language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - nasm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nasm; fi

script:
  - make test && ./tests/test
